require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.alpha"
require "user.colorscheme"
require "user.cmp" -- Slowdown on massive files, need to turn it off
--require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.autopairs"
require "user.cinnamon" -- Smooth Scrolling
require "user.gitsigns"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.whichkey"
require "user.autocommands"
require "user.dap"
require "user.nvim-tree"
require "user.indentline" -- Massive Slowdown on massive files, need to turn it off
